after_script:
  - 'if [[ `node --version` =~ ^v14 && $PG_VERSION == 13]] ; then npm run coverage ; npm install codeclimate-test-reporter ; codeclimate-test-reporter < coverage/lcov.info ; fi'
before_install:
  - 'sudo service postgresql stop'
  - 'sudo service postgresql restart $PG_VERSION'
before_script:
  - 'psql -c "CREATE DATABASE sedentary;" -U postgres'
  - 'psql -c "ALTER DATABASE sedentary SET timezone TO ''GMT'';" -U postgres'
  - 'export SPG=''{"user":"postgres","password":"postgres"}'''
env:
  global:
    - CODECLIMATE_REPO_TOKEN=c7519657dfea145349c1b7a98f7134f033c25f598b40ad5b077744eb4beb7c66
  matrix:
    - PG_VERSION=13
    - PG_VERSION=12
    - PG_VERSION=11
    - PG_VERSION=10
language: node_js
node_js:
  - '14'
  - '12'
  - '10'
sudo: required
